/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.atlassian.jira.rest.client.model.ChangedWorklog;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * List of changed worklogs.
 */
@ApiModel(description = "List of changed worklogs.")
@JsonPropertyOrder({
  ChangedWorklogs.JSON_PROPERTY_VALUES,
  ChangedWorklogs.JSON_PROPERTY_SINCE,
  ChangedWorklogs.JSON_PROPERTY_UNTIL,
  ChangedWorklogs.JSON_PROPERTY_SELF,
  ChangedWorklogs.JSON_PROPERTY_NEXT_PAGE,
  ChangedWorklogs.JSON_PROPERTY_LAST_PAGE
})
@JsonTypeName("ChangedWorklogs")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-31T17:44:39.790417-08:00[America/Los_Angeles]")
public class ChangedWorklogs {
  public static final String JSON_PROPERTY_VALUES = "values";
  private List<ChangedWorklog> values = null;

  public static final String JSON_PROPERTY_SINCE = "since";
  private Long since;

  public static final String JSON_PROPERTY_UNTIL = "until";
  private Long until;

  public static final String JSON_PROPERTY_SELF = "self";
  private URI self;

  public static final String JSON_PROPERTY_NEXT_PAGE = "nextPage";
  private URI nextPage;

  public static final String JSON_PROPERTY_LAST_PAGE = "lastPage";
  private Boolean lastPage;


   /**
   * Changed worklog list.
   * @return values
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Changed worklog list.")
  @JsonProperty(JSON_PROPERTY_VALUES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ChangedWorklog> getValues() {
    return values;
  }




   /**
   * The datetime of the first worklog item in the list.
   * @return since
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The datetime of the first worklog item in the list.")
  @JsonProperty(JSON_PROPERTY_SINCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getSince() {
    return since;
  }




   /**
   * The datetime of the last worklog item in the list.
   * @return until
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The datetime of the last worklog item in the list.")
  @JsonProperty(JSON_PROPERTY_UNTIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getUntil() {
    return until;
  }




   /**
   * The URL of this changed worklogs list.
   * @return self
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The URL of this changed worklogs list.")
  @JsonProperty(JSON_PROPERTY_SELF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public URI getSelf() {
    return self;
  }




   /**
   * The URL of the next list of changed worklogs.
   * @return nextPage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The URL of the next list of changed worklogs.")
  @JsonProperty(JSON_PROPERTY_NEXT_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public URI getNextPage() {
    return nextPage;
  }




  public ChangedWorklogs lastPage(Boolean lastPage) {
    
    this.lastPage = lastPage;
    return this;
  }

   /**
   * Get lastPage
   * @return lastPage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LAST_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getLastPage() {
    return lastPage;
  }


  public void setLastPage(Boolean lastPage) {
    this.lastPage = lastPage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChangedWorklogs changedWorklogs = (ChangedWorklogs) o;
    return Objects.equals(this.values, changedWorklogs.values) &&
        Objects.equals(this.since, changedWorklogs.since) &&
        Objects.equals(this.until, changedWorklogs.until) &&
        Objects.equals(this.self, changedWorklogs.self) &&
        Objects.equals(this.nextPage, changedWorklogs.nextPage) &&
        Objects.equals(this.lastPage, changedWorklogs.lastPage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(values, since, until, self, nextPage, lastPage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChangedWorklogs {\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("    since: ").append(toIndentedString(since)).append("\n");
    sb.append("    until: ").append(toIndentedString(until)).append("\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    nextPage: ").append(toIndentedString(nextPage)).append("\n");
    sb.append("    lastPage: ").append(toIndentedString(lastPage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

