/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.atlassian.jira.rest.client.model.EntityProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Details of a changed worklog.
 */
@ApiModel(description = "Details of a changed worklog.")
@JsonPropertyOrder({
  ChangedWorklog.JSON_PROPERTY_WORKLOG_ID,
  ChangedWorklog.JSON_PROPERTY_UPDATED_TIME,
  ChangedWorklog.JSON_PROPERTY_PROPERTIES
})
@JsonTypeName("ChangedWorklog")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-31T17:44:39.790417-08:00[America/Los_Angeles]")
public class ChangedWorklog {
  public static final String JSON_PROPERTY_WORKLOG_ID = "worklogId";
  private Long worklogId;

  public static final String JSON_PROPERTY_UPDATED_TIME = "updatedTime";
  private Long updatedTime;

  public static final String JSON_PROPERTY_PROPERTIES = "properties";
  private List<EntityProperty> properties = null;


   /**
   * The ID of the worklog.
   * @return worklogId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the worklog.")
  @JsonProperty(JSON_PROPERTY_WORKLOG_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getWorklogId() {
    return worklogId;
  }




   /**
   * The datetime of the change.
   * @return updatedTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The datetime of the change.")
  @JsonProperty(JSON_PROPERTY_UPDATED_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getUpdatedTime() {
    return updatedTime;
  }




   /**
   * Details of properties associated with the change.
   * @return properties
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Details of properties associated with the change.")
  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<EntityProperty> getProperties() {
    return properties;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChangedWorklog changedWorklog = (ChangedWorklog) o;
    return Objects.equals(this.worklogId, changedWorklog.worklogId) &&
        Objects.equals(this.updatedTime, changedWorklog.updatedTime) &&
        Objects.equals(this.properties, changedWorklog.properties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(worklogId, updatedTime, properties);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChangedWorklog {\n");
    sb.append("    worklogId: ").append(toIndentedString(worklogId)).append("\n");
    sb.append("    updatedTime: ").append(toIndentedString(updatedTime)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

