/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.atlassian.jira.rest.client.model.RuleConfiguration;
import com.atlassian.jira.rest.client.model.WorkflowTransition;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * A workflow transition rule.
 */
@ApiModel(description = "A workflow transition rule.")
@JsonPropertyOrder({
  ConnectWorkflowTransitionRule.JSON_PROPERTY_ID,
  ConnectWorkflowTransitionRule.JSON_PROPERTY_KEY,
  ConnectWorkflowTransitionRule.JSON_PROPERTY_CONFIGURATION,
  ConnectWorkflowTransitionRule.JSON_PROPERTY_TRANSITION
})
@JsonTypeName("ConnectWorkflowTransitionRule")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-31T17:44:39.790417-08:00[America/Los_Angeles]")
public class ConnectWorkflowTransitionRule {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_KEY = "key";
  private String key;

  public static final String JSON_PROPERTY_CONFIGURATION = "configuration";
  private RuleConfiguration _configuration;

  public static final String JSON_PROPERTY_TRANSITION = "transition";
  private WorkflowTransition transition = null;


  public ConnectWorkflowTransitionRule id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The ID of the transition rule.
   * @return id
  **/
  @ApiModelProperty(required = true, value = "The ID of the transition rule.")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


   /**
   * The key of the rule, as defined in the Connect app descriptor.
   * @return key
  **/
  @ApiModelProperty(required = true, value = "The key of the rule, as defined in the Connect app descriptor.")
  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getKey() {
    return key;
  }




  public ConnectWorkflowTransitionRule _configuration(RuleConfiguration _configuration) {
    
    this._configuration = _configuration;
    return this;
  }

   /**
   * Get _configuration
   * @return _configuration
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public RuleConfiguration getConfiguration() {
    return _configuration;
  }


  public void setConfiguration(RuleConfiguration _configuration) {
    this._configuration = _configuration;
  }


   /**
   * Get transition
   * @return transition
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRANSITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public WorkflowTransition getTransition() {
    return transition;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectWorkflowTransitionRule connectWorkflowTransitionRule = (ConnectWorkflowTransitionRule) o;
    return Objects.equals(this.id, connectWorkflowTransitionRule.id) &&
        Objects.equals(this.key, connectWorkflowTransitionRule.key) &&
        Objects.equals(this._configuration, connectWorkflowTransitionRule._configuration) &&
        Objects.equals(this.transition, connectWorkflowTransitionRule.transition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, key, _configuration, transition);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectWorkflowTransitionRule {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    _configuration: ").append(toIndentedString(_configuration)).append("\n");
    sb.append("    transition: ").append(toIndentedString(transition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

