/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Details of an operation to perform on a field.
 */
@ApiModel(description = "Details of an operation to perform on a field.")
@JsonPropertyOrder({
  FieldUpdateOperation.JSON_PROPERTY_ADD,
  FieldUpdateOperation.JSON_PROPERTY_SET,
  FieldUpdateOperation.JSON_PROPERTY_REMOVE,
  FieldUpdateOperation.JSON_PROPERTY_EDIT
})
@JsonTypeName("FieldUpdateOperation")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-31T17:44:39.790417-08:00[America/Los_Angeles]")
public class FieldUpdateOperation {
  public static final String JSON_PROPERTY_ADD = "add";
  private JsonNullable<Object> add = JsonNullable.<Object>of(null);

  public static final String JSON_PROPERTY_SET = "set";
  private JsonNullable<Object> set = JsonNullable.<Object>of(null);

  public static final String JSON_PROPERTY_REMOVE = "remove";
  private JsonNullable<Object> remove = JsonNullable.<Object>of(null);

  public static final String JSON_PROPERTY_EDIT = "edit";
  private JsonNullable<Object> edit = JsonNullable.<Object>of(null);


  public FieldUpdateOperation add(Object add) {
    this.add = JsonNullable.<Object>of(add);
    
    return this;
  }

   /**
   * A map containing the name of a field and the value to add to it.
   * @return add
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"labels\":\"Training\",\"issuelinks\":{\"id\":10001}}", value = "A map containing the name of a field and the value to add to it.")
  @JsonIgnore

  public Object getAdd() {
        return add.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ADD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getAdd_JsonNullable() {
    return add;
  }
  
  @JsonProperty(JSON_PROPERTY_ADD)
  public void setAdd_JsonNullable(JsonNullable<Object> add) {
    this.add = add;
  }

  public void setAdd(Object add) {
    this.add = JsonNullable.<Object>of(add);
  }


  public FieldUpdateOperation set(Object set) {
    this.set = JsonNullable.<Object>of(set);
    
    return this;
  }

   /**
   * A map containing the name of a field and the value to set in it.
   * @return set
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"summary\":\"A new summary\",\"issuetype\":{\"id\":10010}}", value = "A map containing the name of a field and the value to set in it.")
  @JsonIgnore

  public Object getSet() {
        return set.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getSet_JsonNullable() {
    return set;
  }
  
  @JsonProperty(JSON_PROPERTY_SET)
  public void setSet_JsonNullable(JsonNullable<Object> set) {
    this.set = set;
  }

  public void setSet(Object set) {
    this.set = JsonNullable.<Object>of(set);
  }


  public FieldUpdateOperation remove(Object remove) {
    this.remove = JsonNullable.<Object>of(remove);
    
    return this;
  }

   /**
   * A map containing the name of a field and the value to removed from it.
   * @return remove
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"labels\":\"Training\",\"components\":{\"id\":10017}}", value = "A map containing the name of a field and the value to removed from it.")
  @JsonIgnore

  public Object getRemove() {
        return remove.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_REMOVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getRemove_JsonNullable() {
    return remove;
  }
  
  @JsonProperty(JSON_PROPERTY_REMOVE)
  public void setRemove_JsonNullable(JsonNullable<Object> remove) {
    this.remove = remove;
  }

  public void setRemove(Object remove) {
    this.remove = JsonNullable.<Object>of(remove);
  }


  public FieldUpdateOperation edit(Object edit) {
    this.edit = JsonNullable.<Object>of(edit);
    
    return this;
  }

   /**
   * A map containing the name of a field and the value to edit in it.
   * @return edit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"timetracking\":{\"key\":\"JIRA\"}}", value = "A map containing the name of a field and the value to edit in it.")
  @JsonIgnore

  public Object getEdit() {
        return edit.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_EDIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getEdit_JsonNullable() {
    return edit;
  }
  
  @JsonProperty(JSON_PROPERTY_EDIT)
  public void setEdit_JsonNullable(JsonNullable<Object> edit) {
    this.edit = edit;
  }

  public void setEdit(Object edit) {
    this.edit = JsonNullable.<Object>of(edit);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FieldUpdateOperation fieldUpdateOperation = (FieldUpdateOperation) o;
    return Objects.equals(this.add, fieldUpdateOperation.add) &&
        Objects.equals(this.set, fieldUpdateOperation.set) &&
        Objects.equals(this.remove, fieldUpdateOperation.remove) &&
        Objects.equals(this.edit, fieldUpdateOperation.edit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(add, set, remove, edit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FieldUpdateOperation {\n");
    sb.append("    add: ").append(toIndentedString(add)).append("\n");
    sb.append("    set: ").append(toIndentedString(set)).append("\n");
    sb.append("    remove: ").append(toIndentedString(remove)).append("\n");
    sb.append("    edit: ").append(toIndentedString(edit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

