/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * HierarchyLevel
 */
@JsonPropertyOrder({
  HierarchyLevel.JSON_PROPERTY_ID,
  HierarchyLevel.JSON_PROPERTY_NAME,
  HierarchyLevel.JSON_PROPERTY_ABOVE_LEVEL_ID,
  HierarchyLevel.JSON_PROPERTY_BELOW_LEVEL_ID,
  HierarchyLevel.JSON_PROPERTY_PROJECT_CONFIGURATION_ID,
  HierarchyLevel.JSON_PROPERTY_ISSUE_TYPE_IDS,
  HierarchyLevel.JSON_PROPERTY_EXTERNAL_UUID,
  HierarchyLevel.JSON_PROPERTY_GLOBAL_HIERARCHY_LEVEL
})
@JsonTypeName("HierarchyLevel")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-31T17:44:39.790417-08:00[America/Los_Angeles]")
public class HierarchyLevel {
  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_ABOVE_LEVEL_ID = "aboveLevelId";
  private Long aboveLevelId;

  public static final String JSON_PROPERTY_BELOW_LEVEL_ID = "belowLevelId";
  private Long belowLevelId;

  public static final String JSON_PROPERTY_PROJECT_CONFIGURATION_ID = "projectConfigurationId";
  private Long projectConfigurationId;

  public static final String JSON_PROPERTY_ISSUE_TYPE_IDS = "issueTypeIds";
  private List<Long> issueTypeIds = null;

  public static final String JSON_PROPERTY_EXTERNAL_UUID = "externalUuid";
  private UUID externalUuid;

  /**
   * Gets or Sets globalHierarchyLevel
   */
  public enum GlobalHierarchyLevelEnum {
    SUBTASK("SUBTASK"),
    
    BASE("BASE"),
    
    EPIC("EPIC");

    private String value;

    GlobalHierarchyLevelEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static GlobalHierarchyLevelEnum fromValue(String value) {
      for (GlobalHierarchyLevelEnum b : GlobalHierarchyLevelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_GLOBAL_HIERARCHY_LEVEL = "globalHierarchyLevel";
  private GlobalHierarchyLevelEnum globalHierarchyLevel;


  public HierarchyLevel id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public HierarchyLevel name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public HierarchyLevel aboveLevelId(Long aboveLevelId) {
    
    this.aboveLevelId = aboveLevelId;
    return this;
  }

   /**
   * Get aboveLevelId
   * @return aboveLevelId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ABOVE_LEVEL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAboveLevelId() {
    return aboveLevelId;
  }


  public void setAboveLevelId(Long aboveLevelId) {
    this.aboveLevelId = aboveLevelId;
  }


  public HierarchyLevel belowLevelId(Long belowLevelId) {
    
    this.belowLevelId = belowLevelId;
    return this;
  }

   /**
   * Get belowLevelId
   * @return belowLevelId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BELOW_LEVEL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getBelowLevelId() {
    return belowLevelId;
  }


  public void setBelowLevelId(Long belowLevelId) {
    this.belowLevelId = belowLevelId;
  }


  public HierarchyLevel projectConfigurationId(Long projectConfigurationId) {
    
    this.projectConfigurationId = projectConfigurationId;
    return this;
  }

   /**
   * Get projectConfigurationId
   * @return projectConfigurationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PROJECT_CONFIGURATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getProjectConfigurationId() {
    return projectConfigurationId;
  }


  public void setProjectConfigurationId(Long projectConfigurationId) {
    this.projectConfigurationId = projectConfigurationId;
  }


  public HierarchyLevel issueTypeIds(List<Long> issueTypeIds) {
    
    this.issueTypeIds = issueTypeIds;
    return this;
  }

  public HierarchyLevel addIssueTypeIdsItem(Long issueTypeIdsItem) {
    if (this.issueTypeIds == null) {
      this.issueTypeIds = new ArrayList<>();
    }
    this.issueTypeIds.add(issueTypeIdsItem);
    return this;
  }

   /**
   * Get issueTypeIds
   * @return issueTypeIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ISSUE_TYPE_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Long> getIssueTypeIds() {
    return issueTypeIds;
  }


  public void setIssueTypeIds(List<Long> issueTypeIds) {
    this.issueTypeIds = issueTypeIds;
  }


  public HierarchyLevel externalUuid(UUID externalUuid) {
    
    this.externalUuid = externalUuid;
    return this;
  }

   /**
   * Get externalUuid
   * @return externalUuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EXTERNAL_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getExternalUuid() {
    return externalUuid;
  }


  public void setExternalUuid(UUID externalUuid) {
    this.externalUuid = externalUuid;
  }


  public HierarchyLevel globalHierarchyLevel(GlobalHierarchyLevelEnum globalHierarchyLevel) {
    
    this.globalHierarchyLevel = globalHierarchyLevel;
    return this;
  }

   /**
   * Get globalHierarchyLevel
   * @return globalHierarchyLevel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GLOBAL_HIERARCHY_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GlobalHierarchyLevelEnum getGlobalHierarchyLevel() {
    return globalHierarchyLevel;
  }


  public void setGlobalHierarchyLevel(GlobalHierarchyLevelEnum globalHierarchyLevel) {
    this.globalHierarchyLevel = globalHierarchyLevel;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HierarchyLevel hierarchyLevel = (HierarchyLevel) o;
    return Objects.equals(this.id, hierarchyLevel.id) &&
        Objects.equals(this.name, hierarchyLevel.name) &&
        Objects.equals(this.aboveLevelId, hierarchyLevel.aboveLevelId) &&
        Objects.equals(this.belowLevelId, hierarchyLevel.belowLevelId) &&
        Objects.equals(this.projectConfigurationId, hierarchyLevel.projectConfigurationId) &&
        Objects.equals(this.issueTypeIds, hierarchyLevel.issueTypeIds) &&
        Objects.equals(this.externalUuid, hierarchyLevel.externalUuid) &&
        Objects.equals(this.globalHierarchyLevel, hierarchyLevel.globalHierarchyLevel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, aboveLevelId, belowLevelId, projectConfigurationId, issueTypeIds, externalUuid, globalHierarchyLevel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HierarchyLevel {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    aboveLevelId: ").append(toIndentedString(aboveLevelId)).append("\n");
    sb.append("    belowLevelId: ").append(toIndentedString(belowLevelId)).append("\n");
    sb.append("    projectConfigurationId: ").append(toIndentedString(projectConfigurationId)).append("\n");
    sb.append("    issueTypeIds: ").append(toIndentedString(issueTypeIds)).append("\n");
    sb.append("    externalUuid: ").append(toIndentedString(externalUuid)).append("\n");
    sb.append("    globalHierarchyLevel: ").append(toIndentedString(globalHierarchyLevel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

