/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.atlassian.jira.rest.client.model.IssueTypeScreenSchemeMapping;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * A list of issue type screen scheme mappings.
 */
@ApiModel(description = "A list of issue type screen scheme mappings.")
@JsonPropertyOrder({
  IssueTypeScreenSchemeMappingDetails.JSON_PROPERTY_ISSUE_TYPE_MAPPINGS
})
@JsonTypeName("IssueTypeScreenSchemeMappingDetails")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-31T17:44:39.790417-08:00[America/Los_Angeles]")
public class IssueTypeScreenSchemeMappingDetails {
  public static final String JSON_PROPERTY_ISSUE_TYPE_MAPPINGS = "issueTypeMappings";
  private List<IssueTypeScreenSchemeMapping> issueTypeMappings = new ArrayList<>();


  public IssueTypeScreenSchemeMappingDetails issueTypeMappings(List<IssueTypeScreenSchemeMapping> issueTypeMappings) {
    
    this.issueTypeMappings = issueTypeMappings;
    return this;
  }

  public IssueTypeScreenSchemeMappingDetails addIssueTypeMappingsItem(IssueTypeScreenSchemeMapping issueTypeMappingsItem) {
    this.issueTypeMappings.add(issueTypeMappingsItem);
    return this;
  }

   /**
   * The list of issue type to screen scheme mappings. A *default* entry cannot be specified because a default entry is added when an issue type screen scheme is created.
   * @return issueTypeMappings
  **/
  @ApiModelProperty(required = true, value = "The list of issue type to screen scheme mappings. A *default* entry cannot be specified because a default entry is added when an issue type screen scheme is created.")
  @JsonProperty(JSON_PROPERTY_ISSUE_TYPE_MAPPINGS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<IssueTypeScreenSchemeMapping> getIssueTypeMappings() {
    return issueTypeMappings;
  }


  public void setIssueTypeMappings(List<IssueTypeScreenSchemeMapping> issueTypeMappings) {
    this.issueTypeMappings = issueTypeMappings;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssueTypeScreenSchemeMappingDetails issueTypeScreenSchemeMappingDetails = (IssueTypeScreenSchemeMappingDetails) o;
    return Objects.equals(this.issueTypeMappings, issueTypeScreenSchemeMappingDetails.issueTypeMappings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(issueTypeMappings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IssueTypeScreenSchemeMappingDetails {\n");
    sb.append("    issueTypeMappings: ").append(toIndentedString(issueTypeMappings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

