/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Details of an issue type scheme and its associated issue types.
 */
@ApiModel(description = "Details of an issue type scheme and its associated issue types.")
@JsonPropertyOrder({
  IssueTypeSchemeDetails.JSON_PROPERTY_NAME,
  IssueTypeSchemeDetails.JSON_PROPERTY_DESCRIPTION,
  IssueTypeSchemeDetails.JSON_PROPERTY_DEFAULT_ISSUE_TYPE_ID,
  IssueTypeSchemeDetails.JSON_PROPERTY_ISSUE_TYPE_IDS
})
@JsonTypeName("IssueTypeSchemeDetails")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-31T17:44:39.790417-08:00[America/Los_Angeles]")
public class IssueTypeSchemeDetails {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_DEFAULT_ISSUE_TYPE_ID = "defaultIssueTypeId";
  private String defaultIssueTypeId;

  public static final String JSON_PROPERTY_ISSUE_TYPE_IDS = "issueTypeIds";
  private List<String> issueTypeIds = new ArrayList<>();


  public IssueTypeSchemeDetails name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the issue type scheme. The name must be unique. The maximum length is 255 characters.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "The name of the issue type scheme. The name must be unique. The maximum length is 255 characters.")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public IssueTypeSchemeDetails description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * The description of the issue type scheme. The maximum length is 4000 characters.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The description of the issue type scheme. The maximum length is 4000 characters.")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public IssueTypeSchemeDetails defaultIssueTypeId(String defaultIssueTypeId) {
    
    this.defaultIssueTypeId = defaultIssueTypeId;
    return this;
  }

   /**
   * The ID of the default issue type of the issue type scheme. This ID must be included in &#x60;issueTypeIds&#x60;.
   * @return defaultIssueTypeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the default issue type of the issue type scheme. This ID must be included in `issueTypeIds`.")
  @JsonProperty(JSON_PROPERTY_DEFAULT_ISSUE_TYPE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDefaultIssueTypeId() {
    return defaultIssueTypeId;
  }


  public void setDefaultIssueTypeId(String defaultIssueTypeId) {
    this.defaultIssueTypeId = defaultIssueTypeId;
  }


  public IssueTypeSchemeDetails issueTypeIds(List<String> issueTypeIds) {
    
    this.issueTypeIds = issueTypeIds;
    return this;
  }

  public IssueTypeSchemeDetails addIssueTypeIdsItem(String issueTypeIdsItem) {
    this.issueTypeIds.add(issueTypeIdsItem);
    return this;
  }

   /**
   * The list of issue types IDs of the issue type scheme. At least one standard issue type ID is required.
   * @return issueTypeIds
  **/
  @ApiModelProperty(required = true, value = "The list of issue types IDs of the issue type scheme. At least one standard issue type ID is required.")
  @JsonProperty(JSON_PROPERTY_ISSUE_TYPE_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getIssueTypeIds() {
    return issueTypeIds;
  }


  public void setIssueTypeIds(List<String> issueTypeIds) {
    this.issueTypeIds = issueTypeIds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssueTypeSchemeDetails issueTypeSchemeDetails = (IssueTypeSchemeDetails) o;
    return Objects.equals(this.name, issueTypeSchemeDetails.name) &&
        Objects.equals(this.description, issueTypeSchemeDetails.description) &&
        Objects.equals(this.defaultIssueTypeId, issueTypeSchemeDetails.defaultIssueTypeId) &&
        Objects.equals(this.issueTypeIds, issueTypeSchemeDetails.issueTypeIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, defaultIssueTypeId, issueTypeIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IssueTypeSchemeDetails {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    defaultIssueTypeId: ").append(toIndentedString(defaultIssueTypeId)).append("\n");
    sb.append("    issueTypeIds: ").append(toIndentedString(issueTypeIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

