/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * The JQL queries to be converted.
 */
@ApiModel(description = "The JQL queries to be converted.")
@JsonPropertyOrder({
  JQLPersonalDataMigrationRequest.JSON_PROPERTY_QUERY_STRINGS
})
@JsonTypeName("JQLPersonalDataMigrationRequest")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-31T17:44:39.790417-08:00[America/Los_Angeles]")
public class JQLPersonalDataMigrationRequest {
  public static final String JSON_PROPERTY_QUERY_STRINGS = "queryStrings";
  private List<String> queryStrings = null;


  public JQLPersonalDataMigrationRequest queryStrings(List<String> queryStrings) {
    
    this.queryStrings = queryStrings;
    return this;
  }

  public JQLPersonalDataMigrationRequest addQueryStringsItem(String queryStringsItem) {
    if (this.queryStrings == null) {
      this.queryStrings = new ArrayList<>();
    }
    this.queryStrings.add(queryStringsItem);
    return this;
  }

   /**
   * A list of queries with user identifiers. Maximum of 100 queries.
   * @return queryStrings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of queries with user identifiers. Maximum of 100 queries.")
  @JsonProperty(JSON_PROPERTY_QUERY_STRINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getQueryStrings() {
    return queryStrings;
  }


  public void setQueryStrings(List<String> queryStrings) {
    this.queryStrings = queryStrings;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JQLPersonalDataMigrationRequest jqLPersonalDataMigrationRequest = (JQLPersonalDataMigrationRequest) o;
    return Objects.equals(this.queryStrings, jqLPersonalDataMigrationRequest.queryStrings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(queryStrings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JQLPersonalDataMigrationRequest {\n");
    sb.append("    queryStrings: ").append(toIndentedString(queryStrings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

