/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.atlassian.jira.rest.client.model.GroupName;
import com.atlassian.jira.rest.client.model.UserDetails;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Details of the users and groups to receive the notification.
 */
@ApiModel(description = "Details of the users and groups to receive the notification.")
@JsonPropertyOrder({
  NotificationRecipients.JSON_PROPERTY_REPORTER,
  NotificationRecipients.JSON_PROPERTY_ASSIGNEE,
  NotificationRecipients.JSON_PROPERTY_WATCHERS,
  NotificationRecipients.JSON_PROPERTY_VOTERS,
  NotificationRecipients.JSON_PROPERTY_USERS,
  NotificationRecipients.JSON_PROPERTY_GROUPS
})
@JsonTypeName("NotificationRecipients")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-31T17:44:39.790417-08:00[America/Los_Angeles]")
public class NotificationRecipients extends HashMap<String, Object> {
  public static final String JSON_PROPERTY_REPORTER = "reporter";
  private Boolean reporter;

  public static final String JSON_PROPERTY_ASSIGNEE = "assignee";
  private Boolean assignee;

  public static final String JSON_PROPERTY_WATCHERS = "watchers";
  private Boolean watchers;

  public static final String JSON_PROPERTY_VOTERS = "voters";
  private Boolean voters;

  public static final String JSON_PROPERTY_USERS = "users";
  private List<UserDetails> users = null;

  public static final String JSON_PROPERTY_GROUPS = "groups";
  private List<GroupName> groups = null;


  public NotificationRecipients reporter(Boolean reporter) {
    
    this.reporter = reporter;
    return this;
  }

   /**
   * Whether the notification should be sent to the issue&#39;s reporter.
   * @return reporter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether the notification should be sent to the issue's reporter.")
  @JsonProperty(JSON_PROPERTY_REPORTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getReporter() {
    return reporter;
  }


  public void setReporter(Boolean reporter) {
    this.reporter = reporter;
  }


  public NotificationRecipients assignee(Boolean assignee) {
    
    this.assignee = assignee;
    return this;
  }

   /**
   * Whether the notification should be sent to the issue&#39;s assignees.
   * @return assignee
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether the notification should be sent to the issue's assignees.")
  @JsonProperty(JSON_PROPERTY_ASSIGNEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAssignee() {
    return assignee;
  }


  public void setAssignee(Boolean assignee) {
    this.assignee = assignee;
  }


  public NotificationRecipients watchers(Boolean watchers) {
    
    this.watchers = watchers;
    return this;
  }

   /**
   * Whether the notification should be sent to the issue&#39;s watchers.
   * @return watchers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether the notification should be sent to the issue's watchers.")
  @JsonProperty(JSON_PROPERTY_WATCHERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getWatchers() {
    return watchers;
  }


  public void setWatchers(Boolean watchers) {
    this.watchers = watchers;
  }


  public NotificationRecipients voters(Boolean voters) {
    
    this.voters = voters;
    return this;
  }

   /**
   * Whether the notification should be sent to the issue&#39;s voters.
   * @return voters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether the notification should be sent to the issue's voters.")
  @JsonProperty(JSON_PROPERTY_VOTERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getVoters() {
    return voters;
  }


  public void setVoters(Boolean voters) {
    this.voters = voters;
  }


  public NotificationRecipients users(List<UserDetails> users) {
    
    this.users = users;
    return this;
  }

  public NotificationRecipients addUsersItem(UserDetails usersItem) {
    if (this.users == null) {
      this.users = new ArrayList<>();
    }
    this.users.add(usersItem);
    return this;
  }

   /**
   * List of users to receive the notification.
   * @return users
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of users to receive the notification.")
  @JsonProperty(JSON_PROPERTY_USERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UserDetails> getUsers() {
    return users;
  }


  public void setUsers(List<UserDetails> users) {
    this.users = users;
  }


  public NotificationRecipients groups(List<GroupName> groups) {
    
    this.groups = groups;
    return this;
  }

  public NotificationRecipients addGroupsItem(GroupName groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<>();
    }
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * List of groups to receive the notification.
   * @return groups
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of groups to receive the notification.")
  @JsonProperty(JSON_PROPERTY_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<GroupName> getGroups() {
    return groups;
  }


  public void setGroups(List<GroupName> groups) {
    this.groups = groups;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotificationRecipients notificationRecipients = (NotificationRecipients) o;
    return Objects.equals(this.reporter, notificationRecipients.reporter) &&
        Objects.equals(this.assignee, notificationRecipients.assignee) &&
        Objects.equals(this.watchers, notificationRecipients.watchers) &&
        Objects.equals(this.voters, notificationRecipients.voters) &&
        Objects.equals(this.users, notificationRecipients.users) &&
        Objects.equals(this.groups, notificationRecipients.groups) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reporter, assignee, watchers, voters, users, groups, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NotificationRecipients {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    reporter: ").append(toIndentedString(reporter)).append("\n");
    sb.append("    assignee: ").append(toIndentedString(assignee)).append("\n");
    sb.append("    watchers: ").append(toIndentedString(watchers)).append("\n");
    sb.append("    voters: ").append(toIndentedString(voters)).append("\n");
    sb.append("    users: ").append(toIndentedString(users)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

