/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.atlassian.jira.rest.client.model.NotificationRecipients;
import com.atlassian.jira.rest.client.model.NotificationRecipientsRestrictions;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Details about a notification.
 */
@ApiModel(description = "Details about a notification.")
@JsonPropertyOrder({
  Notification.JSON_PROPERTY_SUBJECT,
  Notification.JSON_PROPERTY_TEXT_BODY,
  Notification.JSON_PROPERTY_HTML_BODY,
  Notification.JSON_PROPERTY_TO,
  Notification.JSON_PROPERTY_RESTRICT
})
@JsonTypeName("Notification")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-31T17:44:39.790417-08:00[America/Los_Angeles]")
public class Notification extends HashMap<String, Object> {
  public static final String JSON_PROPERTY_SUBJECT = "subject";
  private String subject;

  public static final String JSON_PROPERTY_TEXT_BODY = "textBody";
  private String textBody;

  public static final String JSON_PROPERTY_HTML_BODY = "htmlBody";
  private String htmlBody;

  public static final String JSON_PROPERTY_TO = "to";
  private NotificationRecipients to = null;

  public static final String JSON_PROPERTY_RESTRICT = "restrict";
  private NotificationRecipientsRestrictions restrict = null;


  public Notification subject(String subject) {
    
    this.subject = subject;
    return this;
  }

   /**
   * The subject of the email notification for the issue. If this is not specified, then the subject is set to the issue key and summary.
   * @return subject
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The subject of the email notification for the issue. If this is not specified, then the subject is set to the issue key and summary.")
  @JsonProperty(JSON_PROPERTY_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubject() {
    return subject;
  }


  public void setSubject(String subject) {
    this.subject = subject;
  }


  public Notification textBody(String textBody) {
    
    this.textBody = textBody;
    return this;
  }

   /**
   * The plain text body of the email notification for the issue.
   * @return textBody
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The plain text body of the email notification for the issue.")
  @JsonProperty(JSON_PROPERTY_TEXT_BODY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTextBody() {
    return textBody;
  }


  public void setTextBody(String textBody) {
    this.textBody = textBody;
  }


  public Notification htmlBody(String htmlBody) {
    
    this.htmlBody = htmlBody;
    return this;
  }

   /**
   * The HTML body of the email notification for the issue.
   * @return htmlBody
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The HTML body of the email notification for the issue.")
  @JsonProperty(JSON_PROPERTY_HTML_BODY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHtmlBody() {
    return htmlBody;
  }


  public void setHtmlBody(String htmlBody) {
    this.htmlBody = htmlBody;
  }


  public Notification to(NotificationRecipients to) {
    
    this.to = to;
    return this;
  }

   /**
   * The recipients of the email notification for the issue.
   * @return to
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The recipients of the email notification for the issue.")
  @JsonProperty(JSON_PROPERTY_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public NotificationRecipients getTo() {
    return to;
  }


  public void setTo(NotificationRecipients to) {
    this.to = to;
  }


  public Notification restrict(NotificationRecipientsRestrictions restrict) {
    
    this.restrict = restrict;
    return this;
  }

   /**
   * Restricts the notifications to users with the specified permissions.
   * @return restrict
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Restricts the notifications to users with the specified permissions.")
  @JsonProperty(JSON_PROPERTY_RESTRICT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public NotificationRecipientsRestrictions getRestrict() {
    return restrict;
  }


  public void setRestrict(NotificationRecipientsRestrictions restrict) {
    this.restrict = restrict;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Notification notification = (Notification) o;
    return Objects.equals(this.subject, notification.subject) &&
        Objects.equals(this.textBody, notification.textBody) &&
        Objects.equals(this.htmlBody, notification.htmlBody) &&
        Objects.equals(this.to, notification.to) &&
        Objects.equals(this.restrict, notification.restrict) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subject, textBody, htmlBody, to, restrict, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Notification {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    textBody: ").append(toIndentedString(textBody)).append("\n");
    sb.append("    htmlBody: ").append(toIndentedString(htmlBody)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    restrict: ").append(toIndentedString(restrict)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

