/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.atlassian.jira.rest.client.model.PermissionScheme;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * List of all permission schemes.
 */
@ApiModel(description = "List of all permission schemes.")
@JsonPropertyOrder({
  PermissionSchemes.JSON_PROPERTY_PERMISSION_SCHEMES
})
@JsonTypeName("PermissionSchemes")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-31T17:44:39.790417-08:00[America/Los_Angeles]")
public class PermissionSchemes {
  public static final String JSON_PROPERTY_PERMISSION_SCHEMES = "permissionSchemes";
  private List<PermissionScheme> permissionSchemes = null;


   /**
   * Permission schemes list.
   * @return permissionSchemes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Permission schemes list.")
  @JsonProperty(JSON_PROPERTY_PERMISSION_SCHEMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PermissionScheme> getPermissionSchemes() {
    return permissionSchemes;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PermissionSchemes permissionSchemes = (PermissionSchemes) o;
    return Objects.equals(this.permissionSchemes, permissionSchemes.permissionSchemes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(permissionSchemes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PermissionSchemes {\n");
    sb.append("    permissionSchemes: ").append(toIndentedString(permissionSchemes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

