/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * The ID of a screen scheme.
 */
@ApiModel(description = "The ID of a screen scheme.")
@JsonPropertyOrder({
  UpdateDefaultScreenScheme.JSON_PROPERTY_SCREEN_SCHEME_ID
})
@JsonTypeName("UpdateDefaultScreenScheme")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-31T17:44:39.790417-08:00[America/Los_Angeles]")
public class UpdateDefaultScreenScheme {
  public static final String JSON_PROPERTY_SCREEN_SCHEME_ID = "screenSchemeId";
  private String screenSchemeId;


  public UpdateDefaultScreenScheme screenSchemeId(String screenSchemeId) {
    
    this.screenSchemeId = screenSchemeId;
    return this;
  }

   /**
   * The ID of the screen scheme.
   * @return screenSchemeId
  **/
  @ApiModelProperty(required = true, value = "The ID of the screen scheme.")
  @JsonProperty(JSON_PROPERTY_SCREEN_SCHEME_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getScreenSchemeId() {
    return screenSchemeId;
  }


  public void setScreenSchemeId(String screenSchemeId) {
    this.screenSchemeId = screenSchemeId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateDefaultScreenScheme updateDefaultScreenScheme = (UpdateDefaultScreenScheme) o;
    return Objects.equals(this.screenSchemeId, updateDefaultScreenScheme.screenSchemeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(screenSchemeId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateDefaultScreenScheme {\n");
    sb.append("    screenSchemeId: ").append(toIndentedString(screenSchemeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

