/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.atlassian.jira.rest.client.model.WorkflowScheme;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * A workflow scheme along with a list of projects that use it.
 */
@ApiModel(description = "A workflow scheme along with a list of projects that use it.")
@JsonPropertyOrder({
  WorkflowSchemeAssociations.JSON_PROPERTY_PROJECT_IDS,
  WorkflowSchemeAssociations.JSON_PROPERTY_WORKFLOW_SCHEME
})
@JsonTypeName("WorkflowSchemeAssociations")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-31T17:44:39.790417-08:00[America/Los_Angeles]")
public class WorkflowSchemeAssociations {
  public static final String JSON_PROPERTY_PROJECT_IDS = "projectIds";
  private List<String> projectIds = new ArrayList<>();

  public static final String JSON_PROPERTY_WORKFLOW_SCHEME = "workflowScheme";
  private WorkflowScheme workflowScheme = null;


  public WorkflowSchemeAssociations projectIds(List<String> projectIds) {
    
    this.projectIds = projectIds;
    return this;
  }

  public WorkflowSchemeAssociations addProjectIdsItem(String projectIdsItem) {
    this.projectIds.add(projectIdsItem);
    return this;
  }

   /**
   * The list of projects that use the workflow scheme.
   * @return projectIds
  **/
  @ApiModelProperty(required = true, value = "The list of projects that use the workflow scheme.")
  @JsonProperty(JSON_PROPERTY_PROJECT_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getProjectIds() {
    return projectIds;
  }


  public void setProjectIds(List<String> projectIds) {
    this.projectIds = projectIds;
  }


  public WorkflowSchemeAssociations workflowScheme(WorkflowScheme workflowScheme) {
    
    this.workflowScheme = workflowScheme;
    return this;
  }

   /**
   * The workflow scheme.
   * @return workflowScheme
  **/
  @ApiModelProperty(required = true, value = "The workflow scheme.")
  @JsonProperty(JSON_PROPERTY_WORKFLOW_SCHEME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public WorkflowScheme getWorkflowScheme() {
    return workflowScheme;
  }


  public void setWorkflowScheme(WorkflowScheme workflowScheme) {
    this.workflowScheme = workflowScheme;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowSchemeAssociations workflowSchemeAssociations = (WorkflowSchemeAssociations) o;
    return Objects.equals(this.projectIds, workflowSchemeAssociations.projectIds) &&
        Objects.equals(this.workflowScheme, workflowSchemeAssociations.workflowScheme);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectIds, workflowScheme);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowSchemeAssociations {\n");
    sb.append("    projectIds: ").append(toIndentedString(projectIds)).append("\n");
    sb.append("    workflowScheme: ").append(toIndentedString(workflowScheme)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

