/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.atlassian.jira.rest.client.model.WorkflowTransitionRulesUpdateErrorDetails;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Details of any errors encountered while updating workflow transition rules.
 */
@ApiModel(description = "Details of any errors encountered while updating workflow transition rules.")
@JsonPropertyOrder({
  WorkflowTransitionRulesUpdateErrors.JSON_PROPERTY_UPDATE_RESULTS
})
@JsonTypeName("WorkflowTransitionRulesUpdateErrors")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-31T17:44:39.790417-08:00[America/Los_Angeles]")
public class WorkflowTransitionRulesUpdateErrors {
  public static final String JSON_PROPERTY_UPDATE_RESULTS = "updateResults";
  private List<WorkflowTransitionRulesUpdateErrorDetails> updateResults = new ArrayList<>();


  public WorkflowTransitionRulesUpdateErrors updateResults(List<WorkflowTransitionRulesUpdateErrorDetails> updateResults) {
    
    this.updateResults = updateResults;
    return this;
  }

  public WorkflowTransitionRulesUpdateErrors addUpdateResultsItem(WorkflowTransitionRulesUpdateErrorDetails updateResultsItem) {
    this.updateResults.add(updateResultsItem);
    return this;
  }

   /**
   * A list of workflows.
   * @return updateResults
  **/
  @ApiModelProperty(required = true, value = "A list of workflows.")
  @JsonProperty(JSON_PROPERTY_UPDATE_RESULTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<WorkflowTransitionRulesUpdateErrorDetails> getUpdateResults() {
    return updateResults;
  }


  public void setUpdateResults(List<WorkflowTransitionRulesUpdateErrorDetails> updateResults) {
    this.updateResults = updateResults;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowTransitionRulesUpdateErrors workflowTransitionRulesUpdateErrors = (WorkflowTransitionRulesUpdateErrors) o;
    return Objects.equals(this.updateResults, workflowTransitionRulesUpdateErrors.updateResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(updateResults);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowTransitionRulesUpdateErrors {\n");
    sb.append("    updateResults: ").append(toIndentedString(updateResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

