/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.api;

import com.atlassian.jira.rest.client.model.ContainerForRegisteredWebhooks;
import com.atlassian.jira.rest.client.model.ContainerForWebhookIDs;
import com.atlassian.jira.rest.client.model.ErrorCollection;
import com.atlassian.jira.rest.client.model.FailedWebhooks;
import com.atlassian.jira.rest.client.model.PageBeanWebhook;
import com.atlassian.jira.rest.client.model.WebhookRegistrationDetails;
import com.atlassian.jira.rest.client.model.WebhooksExpirationDate;
import org.junit.Test;
import org.junit.Ignore;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WebhooksApi
 */
@Ignore
public class WebhooksApiTest {

    private final WebhooksApi api = new WebhooksApi();

    
    /**
     * Delete webhooks by ID
     *
     * Removes webhooks by ID. Only webhooks registered by the calling Connect app are removed. If webhooks created by other apps are specified, they are ignored.  **[Permissions](#permissions) required:** Only [Connect apps](https://developer.atlassian.com/cloud/jira/platform/integrating-with-jira-cloud/#atlassian-connect) can use this operation.
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void deleteWebhookByIdTest() throws IOException {
        ContainerForWebhookIDs containerForWebhookIDs = null;
        api.deleteWebhookById(containerForWebhookIDs);

        // TODO: test validations
    }
    
    /**
     * Get dynamic webhooks for app
     *
     * Returns a [paginated](#pagination) list of the webhooks registered by the calling app.  **[Permissions](#permissions) required:** Only [Connect apps](https://developer.atlassian.com/cloud/jira/platform/integrating-with-jira-cloud/#atlassian-connect) can use this operation.
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void getDynamicWebhooksForAppTest() throws IOException {
        Long startAt = null;
        Integer maxResults = null;
        PageBeanWebhook response = api.getDynamicWebhooksForApp(startAt, maxResults);

        // TODO: test validations
    }
    
    /**
     * Get failed webhooks
     *
     * Returns webhooks that have recently failed to be delivered to the requesting app after the maximum number of retries.  After 72 hours the failure may no longer be returned by this operation.  The oldest failure is returned first.  This method uses a cursor-based pagination. To request the next page use the failure time of the last webhook on the list as the &#x60;failedAfter&#x60; value or use the URL provided in &#x60;next&#x60;.  **[Permissions](#permissions) required:** Only [Connect apps](https://developer.atlassian.com/cloud/jira/platform/integrating-with-jira-cloud/#atlassian-connect) can use this operation.
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void getFailedWebhooksTest() throws IOException {
        Integer maxResults = null;
        Long after = null;
        FailedWebhooks response = api.getFailedWebhooks(maxResults, after);

        // TODO: test validations
    }
    
    /**
     * Extend webhook life
     *
     * Webhooks registered through the REST API expire after 30 days. Call this resource periodically to keep them alive.  Unrecognized webhook IDs (nonexistent or belonging to other apps) are ignored.  **[Permissions](#permissions) required:** Only [Connect apps](https://developer.atlassian.com/cloud/jira/platform/integrating-with-jira-cloud/#atlassian-connect) can use this operation.
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void refreshWebhooksTest() throws IOException {
        ContainerForWebhookIDs containerForWebhookIDs = null;
        WebhooksExpirationDate response = api.refreshWebhooks(containerForWebhookIDs);

        // TODO: test validations
    }
    
    /**
     * Register dynamic webhooks
     *
     * Registers webhooks.  **[Permissions](#permissions) required:** Only [Connect apps](https://developer.atlassian.com/cloud/jira/platform/integrating-with-jira-cloud/#atlassian-connect) can use this operation.
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void registerDynamicWebhooksTest() throws IOException {
        WebhookRegistrationDetails webhookRegistrationDetails = null;
        ContainerForRegisteredWebhooks response = api.registerDynamicWebhooks(webhookRegistrationDetails);

        // TODO: test validations
    }
    
}
