/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.model;

import com.atlassian.jira.rest.client.model.RegisteredWebhook;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ContainerForRegisteredWebhooks
 */
public class ContainerForRegisteredWebhooksTest {
    private final ContainerForRegisteredWebhooks model = new ContainerForRegisteredWebhooks();

    /**
     * Model tests for ContainerForRegisteredWebhooks
     */
    @Test
    public void testContainerForRegisteredWebhooks() {
        // TODO: test ContainerForRegisteredWebhooks
    }

    /**
     * Test the property 'webhookRegistrationResult'
     */
    @Test
    public void webhookRegistrationResultTest() {
        // TODO: test webhookRegistrationResult
    }

}
