/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IssueTypeToContextMapping
 */
public class IssueTypeToContextMappingTest {
    private final IssueTypeToContextMapping model = new IssueTypeToContextMapping();

    /**
     * Model tests for IssueTypeToContextMapping
     */
    @Test
    public void testIssueTypeToContextMapping() {
        // TODO: test IssueTypeToContextMapping
    }

    /**
     * Test the property 'contextId'
     */
    @Test
    public void contextIdTest() {
        // TODO: test contextId
    }

    /**
     * Test the property 'issueTypeId'
     */
    @Test
    public void issueTypeIdTest() {
        // TODO: test issueTypeId
    }

    /**
     * Test the property 'isAnyIssueType'
     */
    @Test
    public void isAnyIssueTypeTest() {
        // TODO: test isAnyIssueType
    }

}
