/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.model;

import com.atlassian.jira.rest.client.model.JexpJqlIssues;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for JexpIssues
 */
public class JexpIssuesTest {
    private final JexpIssues model = new JexpIssues();

    /**
     * Model tests for JexpIssues
     */
    @Test
    public void testJexpIssues() {
        // TODO: test JexpIssues
    }

    /**
     * Test the property 'jql'
     */
    @Test
    public void jqlTest() {
        // TODO: test jql
    }

}
