/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.model;

import com.atlassian.jira.rest.client.model.TimeTrackingConfiguration;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ModelConfiguration
 */
public class ModelConfigurationTest {
    private final ModelConfiguration model = new ModelConfiguration();

    /**
     * Model tests for ModelConfiguration
     */
    @Test
    public void testModelConfiguration() {
        // TODO: test ModelConfiguration
    }

    /**
     * Test the property 'votingEnabled'
     */
    @Test
    public void votingEnabledTest() {
        // TODO: test votingEnabled
    }

    /**
     * Test the property 'watchingEnabled'
     */
    @Test
    public void watchingEnabledTest() {
        // TODO: test watchingEnabled
    }

    /**
     * Test the property 'unassignedIssuesAllowed'
     */
    @Test
    public void unassignedIssuesAllowedTest() {
        // TODO: test unassignedIssuesAllowed
    }

    /**
     * Test the property 'subTasksEnabled'
     */
    @Test
    public void subTasksEnabledTest() {
        // TODO: test subTasksEnabled
    }

    /**
     * Test the property 'issueLinkingEnabled'
     */
    @Test
    public void issueLinkingEnabledTest() {
        // TODO: test issueLinkingEnabled
    }

    /**
     * Test the property 'timeTrackingEnabled'
     */
    @Test
    public void timeTrackingEnabledTest() {
        // TODO: test timeTrackingEnabled
    }

    /**
     * Test the property 'attachmentsEnabled'
     */
    @Test
    public void attachmentsEnabledTest() {
        // TODO: test attachmentsEnabled
    }

    /**
     * Test the property 'timeTrackingConfiguration'
     */
    @Test
    public void timeTrackingConfigurationTest() {
        // TODO: test timeTrackingConfiguration
    }

}
