/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.model;

import com.atlassian.jira.rest.client.model.AvatarUrlsBean;
import com.atlassian.jira.rest.client.model.UpdatedProjectCategory;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ProjectForScope
 */
public class ProjectForScopeTest {
    private final ProjectForScope model = new ProjectForScope();

    /**
     * Model tests for ProjectForScope
     */
    @Test
    public void testProjectForScope() {
        // TODO: test ProjectForScope
    }

    /**
     * Test the property 'self'
     */
    @Test
    public void selfTest() {
        // TODO: test self
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'projectTypeKey'
     */
    @Test
    public void projectTypeKeyTest() {
        // TODO: test projectTypeKey
    }

    /**
     * Test the property 'simplified'
     */
    @Test
    public void simplifiedTest() {
        // TODO: test simplified
    }

    /**
     * Test the property 'avatarUrls'
     */
    @Test
    public void avatarUrlsTest() {
        // TODO: test avatarUrls
    }

    /**
     * Test the property 'projectCategory'
     */
    @Test
    public void projectCategoryTest() {
        // TODO: test projectCategory
    }

}
