/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.model;

import com.atlassian.jira.rest.client.model.SecurityScheme;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SecuritySchemes
 */
public class SecuritySchemesTest {
    private final SecuritySchemes model = new SecuritySchemes();

    /**
     * Model tests for SecuritySchemes
     */
    @Test
    public void testSecuritySchemes() {
        // TODO: test SecuritySchemes
    }

    /**
     * Test the property 'issueSecuritySchemes'
     */
    @Test
    public void issueSecuritySchemesTest() {
        // TODO: test issueSecuritySchemes
    }

}
