/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TimeTrackingConfiguration
 */
public class TimeTrackingConfigurationTest {
    private final TimeTrackingConfiguration model = new TimeTrackingConfiguration();

    /**
     * Model tests for TimeTrackingConfiguration
     */
    @Test
    public void testTimeTrackingConfiguration() {
        // TODO: test TimeTrackingConfiguration
    }

    /**
     * Test the property 'workingHoursPerDay'
     */
    @Test
    public void workingHoursPerDayTest() {
        // TODO: test workingHoursPerDay
    }

    /**
     * Test the property 'workingDaysPerWeek'
     */
    @Test
    public void workingDaysPerWeekTest() {
        // TODO: test workingDaysPerWeek
    }

    /**
     * Test the property 'timeFormat'
     */
    @Test
    public void timeFormatTest() {
        // TODO: test timeFormat
    }

    /**
     * Test the property 'defaultUnit'
     */
    @Test
    public void defaultUnitTest() {
        // TODO: test defaultUnit
    }

}
