/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.net.URI;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VersionUnresolvedIssuesCount
 */
public class VersionUnresolvedIssuesCountTest {
    private final VersionUnresolvedIssuesCount model = new VersionUnresolvedIssuesCount();

    /**
     * Model tests for VersionUnresolvedIssuesCount
     */
    @Test
    public void testVersionUnresolvedIssuesCount() {
        // TODO: test VersionUnresolvedIssuesCount
    }

    /**
     * Test the property 'self'
     */
    @Test
    public void selfTest() {
        // TODO: test self
    }

    /**
     * Test the property 'issuesUnresolvedCount'
     */
    @Test
    public void issuesUnresolvedCountTest() {
        // TODO: test issuesUnresolvedCount
    }

    /**
     * Test the property 'issuesCount'
     */
    @Test
    public void issuesCountTest() {
        // TODO: test issuesCount
    }

}
