/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.model;

import com.atlassian.jira.rest.client.model.SimpleLink;
import com.atlassian.jira.rest.client.model.VersionIssuesStatus;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.LocalDate;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Version
 */
public class VersionTest {
    private final Version model = new Version();

    /**
     * Model tests for Version
     */
    @Test
    public void testVersion() {
        // TODO: test Version
    }

    /**
     * Test the property 'expand'
     */
    @Test
    public void expandTest() {
        // TODO: test expand
    }

    /**
     * Test the property 'self'
     */
    @Test
    public void selfTest() {
        // TODO: test self
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'archived'
     */
    @Test
    public void archivedTest() {
        // TODO: test archived
    }

    /**
     * Test the property 'released'
     */
    @Test
    public void releasedTest() {
        // TODO: test released
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'releaseDate'
     */
    @Test
    public void releaseDateTest() {
        // TODO: test releaseDate
    }

    /**
     * Test the property 'overdue'
     */
    @Test
    public void overdueTest() {
        // TODO: test overdue
    }

    /**
     * Test the property 'userStartDate'
     */
    @Test
    public void userStartDateTest() {
        // TODO: test userStartDate
    }

    /**
     * Test the property 'userReleaseDate'
     */
    @Test
    public void userReleaseDateTest() {
        // TODO: test userReleaseDate
    }

    /**
     * Test the property 'project'
     */
    @Test
    public void projectTest() {
        // TODO: test project
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'moveUnfixedIssuesTo'
     */
    @Test
    public void moveUnfixedIssuesToTest() {
        // TODO: test moveUnfixedIssuesTo
    }

    /**
     * Test the property 'operations'
     */
    @Test
    public void operationsTest() {
        // TODO: test operations
    }

    /**
     * Test the property 'issuesStatusForFixVersion'
     */
    @Test
    public void issuesStatusForFixVersionTest() {
        // TODO: test issuesStatusForFixVersion
    }

}
